# Mise configuration for universal version management
# Python is now managed by UV, not mise

[tools]
node = "22"         # Node.js v22 LTS
ruby = "latest"     # Latest stable Ruby
go = "latest"
rust = "stable"     # Stable Rust toolchain

[settings]
experimental = true
legacy_version_file = true  # Support .nvmrc, .ruby-version, etc.
always_keep_download = false
jobs = 4
