# GitHub CLI configuration
# https://cli.github.com/manual/gh_config

# What protocol to use when performing git operations
git_protocol: ssh

# What editor gh should run when creating issues, pull requests, etc
editor: nvim

# When to interactively prompt (always, never)
prompt: enabled

# A pager program to send command output to
pager: less

# Aliases for gh commands
aliases:
    # Workflow shortcuts
    co: pr checkout
    pv: pr view --web
    pc: pr create
    pl: pr list
    
    # Issue shortcuts
    iv: issue view --web
    ic: issue create
    il: issue list
    
    # Repo shortcuts
    rv: repo view --web
    rc: repo clone
    rf: repo fork --clone
    
    # Workflow run shortcuts
    wr: workflow run
    wl: workflow list
    wv: workflow view
    
    # Quick actions
    browse: repo view --web
    clone: repo clone
    fork: repo fork --clone
    pr-ready: pr ready
    pr-draft: pr ready --undo
    
    # Status and overview
    dashboard: |
        !gh api graphql -f query='
        query {
            viewer {
                pullRequests(first: 10, states: OPEN) {
                    nodes {
                        title
                        url
                        repository {
                            nameWithOwner
                        }
                    }
                }
                issues(first: 10, states: OPEN) {
                    nodes {
                        title
                        url
                        repository {
                            nameWithOwner
                        }
                    }
                }
            }
        }
        ' | jq

# Browser to use for opening web pages
browser: