# nreigl.github.io
# Nicolas Reigl
# Path to your oh-my-zsh configuration.
export ZSH="$HOME/.oh-my-zsh"

export TERM="xterm-256color"

# export='usr/local/bin/nvim'
#export EDITOR="nvim"
# export VISUAL=nvim
# export GIT_EDITOR="atom-beta"

# Set name of the theme to load.
ZSH_THEME="powerlevel9k/powerlevel9k"
# ZSH_THEME="spaceship"
# configure powerline for powerlevel9k
POWERLEVEL9K_MODE='nerdfont-complete'
# POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator virtualenv docker_machine)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"

# POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
ZSH_DISABLE_COMPFIX=false

# Ensure languages are set
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(
atom
autoenv
# brew
extract
git-extras
git-flow
github
gitignore
matlab
osx
zsh-pandoc-completion
python
sublime
taskwarrior
tmux
tmuxinator
vi-mode
virtualenv
# virtualenvwrapper
web-search
z
zsh-autosuggestions
# zsh-completions
)

# Zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=white'
# ZSH-completions

# HUB
autoload -Uz compinit && compinit
fpath=(~/.zsh/completions $fpath)


# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

source "$ZSH/oh-my-zsh.sh"

# source /usr/local/share/antigen/antigen.zsh

## User configuration
# sourcing external files
# Settings
source ~/.zsh/settings.zsh

# Bootstrap
source ~/.zsh/bootstrap.zsh

# Aliases
source ~/.zsh/aliases.zsh

# Syntax highlighting
source ~/.zsh/syntax.zsh

# external plugins
source ~/.zsh/plugins/z/z.sh
source /Users/nicolasreigl/.zsh/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh

source ~/.zsh/plugins/conda-auto-env/conda_auto_env.sh

# Don't resolve symbolic links in z
_Z_NO_RESOLVE_SYMLINKS="true"


# Julia version path: Call version  with symnlink eg. julia5 or julia7
# export PATH="/Users/nicolasreigl/github/repos/julia/usr/bin:$PATH" #  Julia Dev (git)
export PATH="/usr/local/opt/julia/bin:$PATH" #  Julia Stable (homebrew)

# Python path
export PYTHONNOUSERSITE="$HOME/.local"

export PYTHONPATH="${PYTHONPATH}:/System/Library/Frameworks/Python.framework/Versions/2.7/bin"

# added by Miniconda3 4.2.12 installer
export PATH="$HOME/miniconda/bin:$PATH"
source /Users/nicolasreigl/miniconda/bin/virtualenvwrapper.sh
source /usr/local/bin/virtualenvwrapper.sh
export WORKON_HOME=$HOME/.virtualenvs   # optional

source /usr/local/opt/autoenv/activate.sh

venvwrap="virtualenvwrapper.sh"
/usr/bin/which -s $venvwrap
if [ $? -eq 0 ]; then
    venvwrap=`/usr/bin/which $venvwrap`
    source $venvwrap
fi

# for zsh completions
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export EDITOR=nvim
